Update to Quarkus 0.19.1
cescoffier/reactive-coffeeshop-demo pull request #2
Opened 2019-07-12 20:30 UTC by kenfinnigan

2019-07-13 14:22 UTC, cescoffier requested changes
There are a few entries that now can be omitted.

2019-07-13 14:22 UTC, cescoffier commented on coffeeshop-service/src/main/resources/application.properties
>  mp.messaging.outgoing.orders.topic=orders
Can be omitted.

2019-07-13 14:22 UTC, cescoffier commented on coffeeshop-service/src/main/resources/application.properties
>  mp.messaging.outgoing.orders.bootstrap.servers=localhost:9092
Can be omitted

2019-07-13 14:22 UTC, cescoffier commented on coffeeshop-service/src/main/resources/application.properties
>  mp.messaging.outgoing.orders.key.serializer=org.apache.kafka.common.serialization.StringSerializer
I believe it can also be omitted.

2019-07-13 14:22 UTC, cescoffier commented on coffeeshop-service/src/main/resources/application.properties
>  mp.messaging.outgoing.orders.acks=1
Can be omitted.

2019-07-13 14:22 UTC, cescoffier commented on coffeeshop-service/src/main/resources/application.properties
>  mp.messaging.outgoing.queue.topic=queue
Can be omitted.

2019-07-13 14:22 UTC, cescoffier commented on coffeeshop-service/src/main/resources/application.properties
>  mp.messaging.incoming.beverages.bootstrap.servers=localhost:9092
can be omitted.

2019-07-13 14:22 UTC, cescoffier commented on coffeeshop-service/src/main/resources/application.properties
>  mp.messaging.outgoing.queue.bootstrap.servers=localhost:9092
can be omitted.

2019-07-13 15:16 UTC, kenfinnigan commented
Is that because the defaults changed?

Will try it out

Sent from my iPhone

> On Jul 13, 2019, at 10:22, Clement Escoffier <notifications@github.com> wrote:
> 
> @cescoffier requested changes on this pull request.
> 
> There are a few entries that now can be omitted.
> 
> In coffeeshop-service/src/main/resources/application.properties:
> 
> > @@ -6,22 +6,22 @@ me.escoffier.quarkus.coffeeshop.http.BaristaService/mp-rest/url=http://localhost
>  
>  
>  ## Orders topic
> -mp.messaging.outgoing.orders.type=io.smallrye.reactive.messaging.kafka.Kafka
> +mp.messaging.outgoing.orders.connector=smallrye-kafka
>  mp.messaging.outgoing.orders.topic=orders
> Can be omitted.
> 
> In coffeeshop-service/src/main/resources/application.properties:
> 
> > @@ -6,22 +6,22 @@ me.escoffier.quarkus.coffeeshop.http.BaristaService/mp-rest/url=http://localhost
>  
>  
>  ## Orders topic
> -mp.messaging.outgoing.orders.type=io.smallrye.reactive.messaging.kafka.Kafka
> +mp.messaging.outgoing.orders.connector=smallrye-kafka
>  mp.messaging.outgoing.orders.topic=orders
>  mp.messaging.outgoing.orders.bootstrap.servers=localhost:9092
> Can be omitted
> 
> In coffeeshop-service/src/main/resources/application.properties:
> 
> > @@ -6,22 +6,22 @@ me.escoffier.quarkus.coffeeshop.http.BaristaService/mp-rest/url=http://localhost
>  
>  
>  ## Orders topic
> -mp.messaging.outgoing.orders.type=io.smallrye.reactive.messaging.kafka.Kafka
> +mp.messaging.outgoing.orders.connector=smallrye-kafka
>  mp.messaging.outgoing.orders.topic=orders
>  mp.messaging.outgoing.orders.bootstrap.servers=localhost:9092
>  mp.messaging.outgoing.orders.key.serializer=org.apache.kafka.common.serialization.StringSerializer
> I believe it can also be omitted.
> 
> In coffeeshop-service/src/main/resources/application.properties:
> 
> > @@ -6,22 +6,22 @@ me.escoffier.quarkus.coffeeshop.http.BaristaService/mp-rest/url=http://localhost
>  
>  
>  ## Orders topic
> -mp.messaging.outgoing.orders.type=io.smallrye.reactive.messaging.kafka.Kafka
> +mp.messaging.outgoing.orders.connector=smallrye-kafka
>  mp.messaging.outgoing.orders.topic=orders
>  mp.messaging.outgoing.orders.bootstrap.servers=localhost:9092
>  mp.messaging.outgoing.orders.key.serializer=org.apache.kafka.common.serialization.StringSerializer
>  mp.messaging.outgoing.orders.value.serializer=org.apache.kafka.common.serialization.StringSerializer
>  mp.messaging.outgoing.orders.acks=1
> Can be omitted.
> 
> In coffeeshop-service/src/main/resources/application.properties:
> 
> >  mp.messaging.incoming.beverages.topic=queue
>  mp.messaging.incoming.beverages.bootstrap.servers=localhost:9092
>  mp.messaging.incoming.beverages.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
>  mp.messaging.incoming.beverages.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
>  
>  ## Queue topic - write
> -mp.messaging.outgoing.queue.type=io.smallrye.reactive.messaging.kafka.Kafka
> +mp.messaging.outgoing.queue.connector=smallrye-kafka
>  mp.messaging.outgoing.queue.topic=queue
> Can be omitted.
> 
> In coffeeshop-service/src/main/resources/application.properties:
> 
> >  mp.messaging.outgoing.orders.topic=orders
>  mp.messaging.outgoing.orders.bootstrap.servers=localhost:9092
>  mp.messaging.outgoing.orders.key.serializer=org.apache.kafka.common.serialization.StringSerializer
>  mp.messaging.outgoing.orders.value.serializer=org.apache.kafka.common.serialization.StringSerializer
>  mp.messaging.outgoing.orders.acks=1
>  
>  ## Beverage / queue topic
> -mp.messaging.incoming.beverages.type=io.smallrye.reactive.messaging.kafka.Kafka
> +mp.messaging.incoming.beverages.connector=smallrye-kafka
>  mp.messaging.incoming.beverages.topic=queue
>  mp.messaging.incoming.beverages.bootstrap.servers=localhost:9092
> can be omitted.
> 
> In coffeeshop-service/src/main/resources/application.properties:
> 
> >  mp.messaging.incoming.beverages.topic=queue
>  mp.messaging.incoming.beverages.bootstrap.servers=localhost:9092
>  mp.messaging.incoming.beverages.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
>  mp.messaging.incoming.beverages.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
>  
>  ## Queue topic - write
> -mp.messaging.outgoing.queue.type=io.smallrye.reactive.messaging.kafka.Kafka
> +mp.messaging.outgoing.queue.connector=smallrye-kafka
>  mp.messaging.outgoing.queue.topic=queue
>  mp.messaging.outgoing.queue.bootstrap.servers=localhost:9092
> can be omitted.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-07-13 15:41 UTC, cescoffier commented
It’s because defaults became smarter.



> On 13 Jul 2019, at 17:16, Ken Finnigan <notifications@github.com> wrote:
> 
> Is that because the defaults changed?
> 
> Will try it out
> 
> Sent from my iPhone
> 
> > On Jul 13, 2019, at 10:22, Clement Escoffier <notifications@github.com> wrote:
> > 
> > @cescoffier requested changes on this pull request.
> > 
> > There are a few entries that now can be omitted.
> > 
> > In coffeeshop-service/src/main/resources/application.properties:
> > 
> > > @@ -6,22 +6,22 @@ me.escoffier.quarkus.coffeeshop.http.BaristaService/mp-rest/url=http://localhost
> > 
> > 
> > ## Orders topic
> > -mp.messaging.outgoing.orders.type=io.smallrye.reactive.messaging.kafka.Kafka
> > +mp.messaging.outgoing.orders.connector=smallrye-kafka
> > mp.messaging.outgoing.orders.topic=orders
> > Can be omitted.
> > 
> > In coffeeshop-service/src/main/resources/application.properties:
> > 
> > > @@ -6,22 +6,22 @@ me.escoffier.quarkus.coffeeshop.http.BaristaService/mp-rest/url=http://localhost
> > 
> > 
> > ## Orders topic
> > -mp.messaging.outgoing.orders.type=io.smallrye.reactive.messaging.kafka.Kafka
> > +mp.messaging.outgoing.orders.connector=smallrye-kafka
> > mp.messaging.outgoing.orders.topic=orders
> > mp.messaging.outgoing.orders.bootstrap.servers=localhost:9092
> > Can be omitted
> > 
> > In coffeeshop-service/src/main/resources/application.properties:
> > 
> > > @@ -6,22 +6,22 @@ me.escoffier.quarkus.coffeeshop.http.BaristaService/mp-rest/url=http://localhost
> > 
> > 
> > ## Orders topic
> > -mp.messaging.outgoing.orders.type=io.smallrye.reactive.messaging.kafka.Kafka
> > +mp.messaging.outgoing.orders.connector=smallrye-kafka
> > mp.messaging.outgoing.orders.topic=orders
> > mp.messaging.outgoing.orders.bootstrap.servers=localhost:9092
> > mp.messaging.outgoing.orders.key.serializer=org.apache.kafka.common.serialization.StringSerializer
> > I believe it can also be omitted.
> > 
> > In coffeeshop-service/src/main/resources/application.properties:
> > 
> > > @@ -6,22 +6,22 @@ me.escoffier.quarkus.coffeeshop.http.BaristaService/mp-rest/url=http://localhost
> > 
> > 
> > ## Orders topic
> > -mp.messaging.outgoing.orders.type=io.smallrye.reactive.messaging.kafka.Kafka
> > +mp.messaging.outgoing.orders.connector=smallrye-kafka
> > mp.messaging.outgoing.orders.topic=orders
> > mp.messaging.outgoing.orders.bootstrap.servers=localhost:9092
> > mp.messaging.outgoing.orders.key.serializer=org.apache.kafka.common.serialization.StringSerializer
> > mp.messaging.outgoing.orders.value.serializer=org.apache.kafka.common.serialization.StringSerializer
> > mp.messaging.outgoing.orders.acks=1
> > Can be omitted.
> > 
> > In coffeeshop-service/src/main/resources/application.properties:
> > 
> > > mp.messaging.incoming.beverages.topic=queue
> > mp.messaging.incoming.beverages.bootstrap.servers=localhost:9092
> > mp.messaging.incoming.beverages.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
> > mp.messaging.incoming.beverages.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
> > 
> > ## Queue topic - write
> > -mp.messaging.outgoing.queue.type=io.smallrye.reactive.messaging.kafka.Kafka
> > +mp.messaging.outgoing.queue.connector=smallrye-kafka
> > mp.messaging.outgoing.queue.topic=queue
> > Can be omitted.
> > 
> > In coffeeshop-service/src/main/resources/application.properties:
> > 
> > > mp.messaging.outgoing.orders.topic=orders
> > mp.messaging.outgoing.orders.bootstrap.servers=localhost:9092
> > mp.messaging.outgoing.orders.key.serializer=org.apache.kafka.common.serialization.StringSerializer
> > mp.messaging.outgoing.orders.value.serializer=org.apache.kafka.common.serialization.StringSerializer
> > mp.messaging.outgoing.orders.acks=1
> > 
> > ## Beverage / queue topic
> > -mp.messaging.incoming.beverages.type=io.smallrye.reactive.messaging.kafka.Kafka
> > +mp.messaging.incoming.beverages.connector=smallrye-kafka
> > mp.messaging.incoming.beverages.topic=queue
> > mp.messaging.incoming.beverages.bootstrap.servers=localhost:9092
> > can be omitted.
> > 
> > In coffeeshop-service/src/main/resources/application.properties:
> > 
> > > mp.messaging.incoming.beverages.topic=queue
> > mp.messaging.incoming.beverages.bootstrap.servers=localhost:9092
> > mp.messaging.incoming.beverages.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
> > mp.messaging.incoming.beverages.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
> > 
> > ## Queue topic - write
> > -mp.messaging.outgoing.queue.type=io.smallrye.reactive.messaging.kafka.Kafka
> > +mp.messaging.outgoing.queue.connector=smallrye-kafka
> > mp.messaging.outgoing.queue.topic=queue
> > mp.messaging.outgoing.queue.bootstrap.servers=localhost:9092
> > can be omitted.
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/cescoffier/quarkus-coffeeshop-demo/pull/2?email_source=notifications&email_token=AADCG7J4NWWXIJKTMYINW3TP7HWTVA5CNFSM4ICQZNOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZ3TQ6Q#issuecomment-511129722>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AADCG7OM334ZTWD72CUOJ6DP7HWTVANCNFSM4ICQZNOA>.
>

2019-07-15 12:46 UTC, kenfinnigan commented
So I was able to remove the config for most stuff, but as soon as I touch the config for "beverages", which the UI uses as a `Publisher`, the UI no longer shows the events.

It looks like everything is still being processed properly, it's just the UI isn't showing events.

Will try and look more deeply later

2019-07-15 13:30 UTC, cescoffier commented
Be aware that beverage channel name does not match the topic name. In this case, topic must be set.

2019-07-15 13:37 UTC, kenfinnigan commented
Thanks for the tip, hadn't twigged to that!

Another round of removals sent

2019-07-15 13:54 UTC, cescoffier approved these changes

2019-07-15 13:54 UTC, merged